services:
  user-search-service:
    build:
      context: .
      dockerfile: Dockerfile.fixed
    container_name: user-search-service
    ports:
      - "8084:8084"
    environment:
      - PORT=8084
      - ENVIRONMENT=development
      - REDIS_URL=redis://localhost:6379
      - SKIP_DB_INIT=true
    restart: unless-stopped 